View(APPENC09)
mnist_data <- read.csv("~/Downloads/mnist.csv", header=FALSE)
pcamn <- princomp(mnist_data)
mnist_data <- read.csv("~/Downloads/mnist.csv", sep=';')
pcamn <- princomp(mnist_data)
View(mnist_data)
View(mnist1)
mnist <- read.csv("~/Downloads/mnist.csv", header=FALSE)
View(mnist)
wine <- read.csv("~/Downloads/winequality-red.csv", sep=";")
View(mnist)
mnist_data  <- mnist[,-1]
pca_mnist <- princomp(mnist_data)
View(mnist_data)
pca <- princomp(wine)
summary(pca)
loadings(pcs)
loadings(pca)
library("corrplot", lib.loc="~/Library/R/3.2/library")
library("ggplot2", lib.loc="~/Library/R/3.2/library")
library("e1071", lib.loc="~/Library/R/3.2/library")
library("mvoutlier", lib.loc="~/Library/R/3.2/library")
pca_mnist <- princomp(mnist_dataplot)
